/*
 * File: app/controller/RegisterController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coffeeshop.controller.RegisterController', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'RegisterPanel',
            'HomePanel'
        ],

        control: {
            "button#registerback": {
                tap: 'registerBackTapped'
            },
            "button#registerDoneButton": {
                tap: 'registerDoneTapped'
            }
        }
    },

    registerBackTapped: function(button, e, eOpts) {
        var navigationView = button.up('#mainnavview');
        navigationView.pop();
    },

    registerDoneTapped: function(button, e, eOpts) {
        var panel = button.up('panel'),
            usernameField = panel.down('#username'),
            passwordField = panel.down('#password'),
            confirmField = panel.down('#confirm'),
            username = usernameField.getValue(),
            password = passwordField.getValue(),
            confirm = confirmField.getValue();

        // Check username is valid and unique

        // Check password and confirm match and are safe (min 6 chars)

        // Show homepage
        var navigationView = button.up('#mainnavview');
        navigationView.push(Ext.create('Coffeeshop.view.HomePanel'));
    }

});